import './card.js';
import './page-disable.js';
import './validate.js';
import { validate } from './validate.js';
validate();
import {getMap} from './map.js';
import './price-slider.js';
import './api.js';
import './user-form.js';
getMap();
import './map-filters.js';
import './picture-preview.js';
